
# .github/workflows/norminette.yml
on: [push, pull_request]

jobs:
  norminette_v2_job:
    runs-on: ubuntu-latest
    name: norminette v2
    steps:
    - uses: actions/checkout@v2
    - uses: alexandregv/norminette-action@v2
      with:
        flags: "libft/* ft_printf/* Piscine/*"
